/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ApiEmojisRouteImport } from './routes/api/emojis'
import { Route as EmojiSlugRouteImport } from './routes/emoji.$slug'
import { Route as ApiEmojisSlugRouteImport } from './routes/api/emojis.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmojisRoute = ApiEmojisRouteImport.update({
  id: '/api/emojis',
  path: '/api/emojis',
  getParentRoute: () => rootRouteImport,
} as any)
const EmojiSlugRoute = EmojiSlugRouteImport.update({
  id: '/emoji/$slug',
  path: '/emoji/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmojisSlugRoute = ApiEmojisSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiEmojisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/api/emojis': typeof ApiEmojisRouteWithChildren
  '/emoji/$slug': typeof EmojiSlugRoute
  '/api/emojis/$slug': typeof ApiEmojisSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/api/emojis': typeof ApiEmojisRouteWithChildren
  '/emoji/$slug': typeof EmojiSlugRoute
  '/api/emojis/$slug': typeof ApiEmojisSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/api/emojis': typeof ApiEmojisRouteWithChildren
  '/emoji/$slug': typeof EmojiSlugRoute
  '/api/emojis/$slug': typeof ApiEmojisSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/explore'
    | '/favorites'
    | '/api/emojis'
    | '/emoji/$slug'
    | '/api/emojis/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/explore'
    | '/favorites'
    | '/api/emojis'
    | '/emoji/$slug'
    | '/api/emojis/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/explore'
    | '/favorites'
    | '/api/emojis'
    | '/emoji/$slug'
    | '/api/emojis/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExploreRoute: typeof ExploreRoute
  FavoritesRoute: typeof FavoritesRoute
  ApiEmojisRoute: typeof ApiEmojisRouteWithChildren
  EmojiSlugRoute: typeof EmojiSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/emojis': {
      id: '/api/emojis'
      path: '/api/emojis'
      fullPath: '/api/emojis'
      preLoaderRoute: typeof ApiEmojisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emoji/$slug': {
      id: '/emoji/$slug'
      path: '/emoji/$slug'
      fullPath: '/emoji/$slug'
      preLoaderRoute: typeof EmojiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/emojis/$slug': {
      id: '/api/emojis/$slug'
      path: '/$slug'
      fullPath: '/api/emojis/$slug'
      preLoaderRoute: typeof ApiEmojisSlugRouteImport
      parentRoute: typeof ApiEmojisRoute
    }
  }
}

interface ApiEmojisRouteChildren {
  ApiEmojisSlugRoute: typeof ApiEmojisSlugRoute
}

const ApiEmojisRouteChildren: ApiEmojisRouteChildren = {
  ApiEmojisSlugRoute: ApiEmojisSlugRoute,
}

const ApiEmojisRouteWithChildren = ApiEmojisRoute._addFileChildren(
  ApiEmojisRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExploreRoute: ExploreRoute,
  FavoritesRoute: FavoritesRoute,
  ApiEmojisRoute: ApiEmojisRouteWithChildren,
  EmojiSlugRoute: EmojiSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
